<?php

/**
 * @file
 * Admin interface for the edgerysders_consent module, found at /admin/config/content/consent.
 */

/**
 * Form builder.
 */
 /*
function edgeryders_consent_settings_form($form, &$form_state) {
  $form['edgeryders_consent_variable_foo'] = array(
    '#type' => 'textfield',
    '#title' => t('Foo'),
    '#default_value' => variable_get('edgeryders_consent_variable_foo', 42),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
*/
