<?php

/**
 * @file
 * Provides dialog integration for user.module.
 */

/**
 * Implement hook_block_view_alter().
 */
function dialog_user_block_view_alter(&$data, $block) {
  switch ($block->delta) {
    case 'login':
      // Attach the library for handling the dialog in the response.
      $data['content']['#attached']['library'][] = array('system', 'drupal.ajax');
      break;
  }
}

/**
 * Implement hook_form_FORM_ID_alter().
 */
function dialog_user_form_user_login_block_alter(&$form, &$form_state, $form_id) {
  // Modify the user links.
  if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
    // Use a dialog for creating a new account.
    $items[] = l(t('Create new account'), 'user/register', array(
      'attributes' => array(
        'title' => t('Create a new user account.'),
        'class' => array('use-ajax'),
        'data-dialog' => 'true',
        'data-dialog-options' => '{"width":"50%"}',
      )
    ));
  }
  // Use a dialog for requesting a new password.
  $items[] = l(t('Request new password'), 'user/password', array(
      'attributes' => array(
        'title' => t('Request new password via e-mail.'),
        'class' => array('use-ajax'),
        'data-dialog' => 'true',
        'data-dialog-options' => '{"width":"50%"}',
      ))
  );
  $form['links'] = array(
    '#markup' => theme('item_list', array('items' => $items))
  );
}

/**
 * Implement hook_form_FORM_ID_alter().
 */
function dialog_user_form_user_login_alter(&$form, &$form_state, $form_id) {
  // Make the 'Log in' button the primary action.
  $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
}

/**
 * Implement hook_form_FORM_ID_alter().
 */
function dialog_user_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  // Make the 'Create new account' button the primary action.
  $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
}

/**
 * Implement hook_form_FORM_ID_alter().
 */
function dialog_user_form_user_pass_alter(&$form, &$form_state, $form_id) {
  // Make the 'E-mail new password' button the primary action.
  $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
}
