<?php

/**
 * @file
 * Registering CKEditor divarea plugin.
 */

/**
 * Provides a CKEditor plugin for use with the Drupal ckeditor module.
 *
 * Implementation of hook_ckeditor_plugin().
 */
function ckeditor_divarea_ckeditor_plugin() {
  return array('ckeditor_divarea' => array(
    'name' => 'divarea',
    'desc' => t('Plugin for editing in a div rather than iframe.'),
    'path' => drupal_get_path('module', 'ckeditor_divarea') . '/plugins/divarea/',
  ));
}

/**
 * Provides a CKEditor plugin for use with the Drupal editor_ckeditor module.
 *
 * Implementation of hook_editor_ckeditor_plugins().
 *
 * Documentation: http://cgit.drupalcode.org/editor/tree/modules/editor_ckeditor/editor_ckeditor.api.php#n62
 * (But note, instead of the "location" key, "path" has to be used.)
 */
function ckeditor_divarea_editor_ckeditor_plugins() {
  $plugins['divarea'] = array(
    'path' => drupal_get_path('module', 'ckeditor_divarea') . '/plugins/divarea',
    'file' => 'plugin.js',
    'enabled callback' => TRUE, // Works but undocumented. Normally provide a function name.
  );

  return $plugins;
}

