<?php
/**
 * @file
 */

/**
 * Implements hook_help().
 */
function pmtask_help($path, $arg) {
  $o = '';

  switch ($path) {
    case "admin/help#pmtask":
      $o = '<p>' . t("Provides task support for Project Management") . '</p>';
      break;
  }

  return $o;
}

/**
 * Implements hook_permission().
 */
function pmtask_permission() {
  return array(
    'Project Management Task: access' => array(
      'title' => t('Access Project Management Task'),
    ),
    'Project Management Task: add' => array(
      'title' => t('Add Project Management Tasks'),
    ),
    'Project Management Task: delete all' => array(
      'title' => t('Delete Any Project Management Task'),
    ),
    'Project Management Task: delete own' => array(
      'title' => t('Delete Authored Project Management Task'),
    ),
    'Project Management Task: delete of user organization' => array(
      'title' => t('Delete Project Management Task in own Organization'),
    ),
    'Project Management Task: delete if assigned to task' => array(
      'title' => t('Delete Project Management Task if user assigned to task'),
    ),
    'Project Management Task: edit all' => array(
      'title' => t('Edit Any Project Management Task'),
    ),
    'Project Management Task: edit own' => array(
      'title' => t('Edit Authored Project Management Task'),
    ),
    'Project Management Task: edit of user organization' => array(
      'title' => t('Edit Project Management Task in own Organization'),
    ),
    'Project Management Task: edit if assigned to task' => array(
      'title' => t('Edit Project Management Task if user assigned to task'),
    ),
    'Project Management Task: view all' => array(
      'title' => t('View Any Project Management Task'),
    ),
    'Project Management Task: view own' => array(
      'title' => t('View Authored'),
    ),
    'Project Management Task: view of user organization' => array(
      'title' => t('View Project Management Task in own Organization'),
    ),
    'Project Management Task: view if assigned to task' => array(
      'title' => t('View Project Management Task if user assigned to task'),
    ),
  );
}

/**
 * Implements hook_node_access().
 */
function pmtask_node_access($node, $op, $account = NULL) {
  $type = is_string($node) ? $node : $node->type;
  if ($type == 'pmtask') {
    // If no account is specified, assume that the check is against the current logged in user
    if (is_null($account)) {
      global $user;
      $account = $user;
    }
    if ($op == 'create' AND user_access('Project Management Task: add', $account)) {
      return NODE_ACCESS_ALLOW;
    }
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_menu().
 */
function pmtask_menu() {
  $items['node/%node/tasks'] = array(
    'title' => 'Tasks',
    'page callback' => 'pmtask_tasks',
    'page arguments' => array(1),
    'access callback' => '_pmtask_tasks_access',
    'access arguments' => array(1),
    'file' => 'pmtask.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 4
  );
  $items['pm/project_tasks_js/%'] = array(
    'title' => 'Tasks',
    'page callback' => '_pmtask_project_tasks_js',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'file' => 'pmtask.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['pm/project_assignments_js/%'] = array(
    'title' => 'Assignments',
    'page callback' => '_pmtask_project_assignments_js',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
    'file' => 'pmtask.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/pm/task'] = array(
    'title' => 'Project Management Task',
    'description' => 'Project Management Task administration page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pmtask_admin_settings'),
    'access arguments' => array('Project Management: access administration pages'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Admin settings form for pmtask module.
 */
function pmtask_admin_settings() {
  $form = array();

  $form['pmtask_billable_default'] = array(
    '#type' => 'checkbox',
    '#title' => t('Default Value for billable field.'),
    '#default_value' => variable_get('pmtask_billable_default', FALSE),
    '#description' => t('When checked, Project Management will set the task to billable by default'),
    '#size' => 5,
  );

  $form['pmtask_enable_ganttchart'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Gantt Charts (experimental feature)'),
    '#default_value' => variable_get('pmtask_enable_ganttchart', False),
  );

  $form['pmtask_jsgantt_options'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Chart display options'),
    '#default_value' => variable_get('pmtask_jsgantt_options', array('ShowStartDate', 'ShowEndDate', 'ShowDur')),
    '#options' => array(
      'ShowStartDate' => t('Show start date'),
      'ShowEndDate' => t('Show end date'),
      'ShowDur' => t('Show duration'),
    ),
    '#description' => t('Choose display options for gantt chart.'),
  );

  $form['pmtask_jsgantt_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Gantt chart default color'),
    '#default_value' => variable_get('pmtask_jsgantt_color', '666666'),
    '#description' => t('Enter default color for gantt chart bars.'),
    '#size' => 6,
  );
  $form['pmtask_jsgantt_color_completed'] = array(
    '#type' => 'textfield',
    '#title' => t('Gantt chart "completed" color'),
    '#default_value' => variable_get('pmtask_jsgantt_color_completed', '0DFF24'),
    '#description' => t('Enter "completed" color for gantt chart bars.'),
    '#size' => 6,
  );
  $form['pmtask_jsgantt_color_in_progress'] = array(
    '#type' => 'textfield',
    '#title' => t('Gantt chart "in progress" color'),
    '#default_value' => variable_get('pmtask_jsgantt_color_in_progress', '00CCFF'),
    '#description' => t('Enter "in progress" color for gantt chart bars.'),
    '#size' => 6,
  );
  $form['pmtask_jsgantt_color_on_hold'] = array(
    '#type' => 'textfield',
    '#title' => t('Gantt chart "on hold" color'),
    '#default_value' => variable_get('pmtask_jsgantt_color_on_hold', 'FFF60D'),
    '#description' => t('Enter "on hold" color for gantt chart bars.'),
    '#size' => 6,
  );
  $form['pmtask_jsgantt_color_overdue'] = array(
    '#type' => 'textfield',
    '#title' => t('Gantt chart "overdue" color'),
    '#default_value' => variable_get('pmtask_jsgantt_color_overdue', 'FF0D0D'),
    '#description' => t('Enter "overdue" color for gantt chart bars.'),    '#size' => 6,
  );

  return system_settings_form($form);
}

/**
 * Checks that the JSGantt library is present.
 */
function jsgantt_check_directory($form_element) {
  $file = $form_element['#value'] . "/jsgantt.js";
  if (!file_exists($file)) {
    form_set_error($form_element['#name'], t('The file %file does not exist.', array('%file' => $file)));
  }
  return $form_element;
}

/**
 * Implements hook_theme().
 */
function pmtask_theme() {
  return array(
    'pmtask_tasks' => array(
      'file'      => 'pmtask.theme.inc',
      'arguments' => array('form'),
    ),
    'pmtask_view' => array(
      'file'      => 'pmtask.theme.inc',
      'variables' => array('node', 'view_mode'),
    ),
  );
}

/**
 * Implements hook_node_info().
 */
function pmtask_node_info() {
  return array(
    'pmtask' => array(
      'name' => t('Task'),
      'base' => 'pmtask',
      'description' => t("A task for Project Management."),
      'title_label' => t("Title"),
      'body_label' => t("Description"),
    )
  );
}

/**
 * Implements hook_field_extra_fields().
 */
function pmtask_field_extra_fields() {
  $extra['node']['pmtask'] = array(
    'form' => array(
      'group1' => array(
        'label' => 'Organization/Project/Task/Weight/Step Group',
        'weight' => -20,
      ),
      'group2' => array(
        'label' => 'Category/Status/Priority Group',
        'weight' => -18,
      ),
      'group3' => array(
        'label' => 'Date/Duration Group',
        'weight' => -17,
      ),
      'group4' => array(
        'label' => 'Price Group',
        'weight' => -16,
      ),
      'group5' => array(
        'label' => 'Assigned to',
        'weight' => -15,
      ),
      'group6' => array(
        'label' => 'Billable / Billed Group',
        'weight' => -14,
      ),
    ),
  );
  return $extra;
}

/**
 * Implements hook_field_extra_fields_alter().
 */
function pmtask_field_extra_fields_alter(&$info) {
  $info['node']['pmtask']['form']['title']['weight'] = -19;
}

/**
 * Implements hook_pmorganization_change().
 */
function pmtask_pmorganization_change($organization_nid, $organization_title) {
  db_update('pmtask')
    ->fields(array('organization_title' => $organization_title))
    ->condition('organization_nid', $organization_nid)
    ->execute();
}

/**
 * Implements hook_pmproject_change().
 */
function pmtask_pmproject_change($project_nid, $project_title) {
  db_update('pmproject')
    ->fields(array('project_title' => $project_title))
    ->condition('project_nid', $project_nid)
    ->execute();
}

/**
 * Implements hook_pmproject_change_hierarchy().
 */
function pmtask_pmproject_change_hierarchy($project_nid, $organization_nid, $organization_title) {
  db_update('pmtask')
    ->fields(array(
      'organization_nid' => $organization_nid,
      'organization_title' => $organization_title,
    ))
    ->condition('project_nid', $project_nid)
    ->execute();
}

/**
 * Implements hook_form().
 */
function pmtask_form(&$node, $form_state) {
  $breadcrumb = array();
  $breadcrumb[] = l(t('Project Management'), 'pm');

  if (array_key_exists('project_nid', $_GET)) {
    $breadcrumb[] = l(t('Projects'), 'pm/projects');
    $project = node_load($_GET['project_nid']);
    $breadcrumb[] = l(t('Project : !project', array('!project' => $project->title)), 'node/' . $project->nid);
    $breadcrumb[] = l(t('Tasks'), 'node/' . $project->nid . '/tasks');
  }
  else {
    $breadcrumb[] = l(t('Tasks'), 'pm/tasks');
  }

  drupal_set_breadcrumb($breadcrumb);

  if (arg(1)=='add') {
    $node->datebegin = time();
    $node->dateend = time();

    if (array_key_exists('organization_nid', $_GET) && !$node->organization_nid) {
      $node->organization_nid = $_GET['organization_nid'];
    }
    if (array_key_exists('project_nid', $_GET) && !$node->project_nid) {
      $node->project_nid = $_GET['project_nid'];
      $p = node_load($node->project_nid);
      // Ensure that the correct organization is loaded
      $node->organization_nid = $p->organization_nid;
      if (!pmorganization_node_access($node->organization_nid, 'view')) {
        drupal_set_message(t("You cannot add a task for this project, as you do not have access to view the organization's profile"));
        drupal_goto('node/' . $node->project_nid);
      }
    }
    if (array_key_exists('task_nid', $_GET) && !$node->parent_nid) {
      // Parent task can be autoloaded by use of ?task_nid=string
      $node->parent_nid = $_GET['task_nid'];
      $t = node_load($node->parent_nid);
      // Ensure that the correct project is loaded
      $node->project_nid = $t->project_nid;
      $node->organization_nid = $t->organization_nid;
      // If no parent project then no need to check access rights, there will always be a parent org.
      $project_access = $node->project_nid ? pmproject_access('view', $node->project_nid) : TRUE;
      if (!$project_access || !pmorganization_node_access($node->organization_nid, 'view')) {
        drupal_set_message(t("You cannot add a task with this parent, as you do not have access to view both the organization and project profiles"));
        drupal_goto('node/' . $node->parent_nid);
      }
    }

    if (isset($_SESSION['pmtask_list_filter']['organization_nid']) && $_SESSION['pmtask_list_filter']['organization_nid'] && !$node->organization_nid) {
      $node->organization_nid = $_SESSION['pmtask_list_filter']['organization_nid'];
    }
    if (isset($_SESSION['pmtask_list_filter']['project_nid']) && $_SESSION['pmtask_list_filter']['project_nid'] && !$node->project_nid) {
      $node->project_nid = $_SESSION['pmtask_list_filter']['project_nid'];
    }

    $node->billable = variable_get('pmtask_billable_default', FALSE);
  }

  $type = node_type_get_type($node);
  $info = field_info_extra_fields('node', 'pmtask', 'form');

  $form['#attributes']['class'] = 'pmcomponent_node_form';

  $form['group1'] = array(
    '#type' => 'markup',
    '#theme' => 'pm_form_group',
    '#weight' => $info['group1']['weight'],
  );

  $org_query = db_select('node', 'n');
  $org_query->join('pmorganization', 'sor', 'n.vid = sor.vid');
  $org_result = $org_query
    ->fields('n', array('nid', 'title'))
    ->condition('n.status', 1)
    ->condition('sor.isactive', 1)
    ->condition('n.type', 'pmorganization')
    ->addTag('node_access')
    ->orderBy('n.title', 'ASC')
    ->execute();

  $organizations = array();
  foreach ($org_result as $organization) {
    $organizations[$organization->nid] = $organization->title;
    if (!isset($node->organization_nid)) $node->organization_nid = $organization->nid;
  }
  $form['group1']['organization_nid'] = array(
    '#type' => 'select',
    '#title' => t('Organization'),
    '#default_value' => isset($node->organization_nid) ? $node->organization_nid : NULL,
    '#options' => $organizations,
    '#required' => TRUE,
    '#ajax' => array(
      'callback' => 'pmtask_ajax_organization_nid',
      'wrapper' => 'pmtask-project-nid',
    ),
  );

  if (isset($node->organization_nid)) {
    $organization_nid = isset($form_state['values']['organization_nid']) ? $form_state['values']['organization_nid'] : $node->organization_nid;
  }
  else {
    drupal_set_message(t('Please add an organization to the system before trying to add a task.'), 'error');
    $organization_nid = NULL;
  }

  $pro_query = db_select('node', 'n');
  $pro_query->join('pmproject', 'spr', 'n.vid = spr.vid');
  $pro_result = $pro_query
    ->fields('n', array('nid', 'title'))
    ->condition('n.status', 1)
    ->condition('spr.organization_nid', $organization_nid)
    ->condition('n.type', 'pmproject')
    ->addTag('node_access')
    ->orderBy('n.title', 'ASC')
    ->execute();

  $projects = array();
  foreach ($pro_result as $project) {
    $projects[$project->nid] = $project->title;
    if (!isset($node->project_nid)) $node->project_nid = $project->nid;
  }
  $form['group1']['project_nid'] = array(
    '#type' => 'select',
    '#title' => t('Project'),
    '#default_value' => isset($node->project_nid) ? $node->project_nid : NULL,
    '#options' => $projects,
    '#required' => TRUE,
    '#prefix' => '<div id="pmtask-project-nid">',
    '#suffix' => '</div>',
  );

  $form['group1']['project_nid_old'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($node->project_nid) ? $node->project_nid : NULL,
  );

//  $tree = _pmtask_get_tree($node->project_nid);
//  $parent_tasks = _pmtask_plain_tree($tree);
  $form['group1']['parent_nid'] = array(
    '#type' => 'select',
    '#title' => t('Parent task'),
    '#default_value' => isset($node->parent_nid) ? $node->parent_nid : 0,
    '#options' => array(0 => '-') + array(),// $parent_tasks,
    '#prefix' => '<div id="pmtask-parent-nid">',
    '#suffix' => '</div>',
  );

  $form['group1']['weight'] = array(
    '#type' => 'weight',
    '#title' => t('Weight'),
    '#default_value' => isset($node->weight) ? $node->weight : 0,
  );

  $form['group1']['stepno'] = array(
    '#type' => 'textfield',
    '#title' => t('Step no.'),
    '#size' => 15,
    '#required' => FALSE,
    '#default_value' => isset($node->stepno) ? $node->stepno : NULL,
  );

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => $info['title']['weight'],
  );

  $form['group2'] = array(
    '#type' => 'markup',
    '#theme' => 'pm_form_group',
    '#weight' => $info['group2']['weight'],
  );

  $taskcategory_list = pm_attributes_bydomain('Task category');
  $form['group2']['taskcategory'] = array(
    '#type' => 'select',
    '#title' => t('Category'),
    '#default_value' => $node->taskcategory,
    '#options' => $taskcategory_list['values'],
  );

  $taskstatus_list = pm_attributes_bydomain('Task status');
  $form['group2']['taskstatus'] = array(
    '#type' => 'select',
    '#title' => t('Status'),
    '#default_value' => $node->taskstatus,
    '#options' => $taskstatus_list['values'],
  );

  $taskpriority_list = pm_attributes_bydomain('Task priority');
  $form['group2']['taskpriority'] = array(
    '#type' => 'select',
    '#title' => t('Priority'),
    '#default_value' => $node->taskpriority,
    '#options' => $taskpriority_list['values'],
  );

  $form['group3'] = array(
    '#type' => 'markup',
    '#theme' => 'pm_form_group',
    '#weight' => $info['group3']['weight'],
  );

  $form['group3']['datebegin'] = array(
    '#type' => 'dateext',
    '#title' => t('Date begin'),
    '#withnull' => TRUE,
    '#default_value' => $node->datebegin,
  );

  $form['group3']['dateend'] = array(
    '#type' => 'dateext',
    '#title' => t('Date end'),
    '#withnull' => TRUE,
    '#default_value' => $node->dateend,
  );

  $durationunit_list = pm_attributes_bydomain('Duration unit');
  $form['group3']['durationunit'] = array(
    '#type' => 'select',
    '#title' => t('Duration unit'),
    '#default_value' => $node->durationunit,
    '#options' => $durationunit_list['values'],
  );

  $form['group3']['duration'] = array(
    '#type' => 'textfield',
    '#title' => t('Duration'),
    '#size' => 20,
    '#default_value' => isset($node->duration) ? $node->duration : NULL,
  );

  $form['group4'] = array(
    '#type' => 'markup',
    '#theme' => 'pm_form_group',
    '#weight' => $info['group4']['weight'],
  );

  $pricemode_list = pm_attributes_bydomain('Price mode');
  $form['group4']['pricemode'] = array(
    '#type' => 'select',
    '#title' => t('Price mode'),
    '#default_value' => $node->pricemode,
    '#options' => $pricemode_list['values'],
  );

  $form['group4']['price'] = array(
    '#title' => t('Price'),
    '#type' => 'textfield',
    '#size' => 15,
    '#default_value' => isset($node->price) ? $node->price : NULL,
  );

  $currency_list = pm_attributes_bydomain('Currency');
  $form['group4']['currency'] = array(
    '#type' => 'select',
    '#title' => t('Price currency'),
    '#default_value' => $node->currency,
    '#options' => $currency_list['values'],
  );

  $form['group5'] = array(
    '#type' => 'markup',
    '#theme' => 'pm_form_group',
    '#weight' => $info['group5']['weight'],
  );

  $options = pm_get_assignment_options($node->organization_nid, $node->project_nid);

  $form['group5']['assigned_nid'] = array(
    '#type' => 'select',
    '#title' => t('Assigned to'),
    '#options' => $options,
    '#default_value' => isset($node->assigned_nid) ? $node->assigned_nid : 0,
  );

  $form['group6'] = array(
    '#type' => 'markup',
    '#theme' => 'pm_form_group',
    '#weight' => $info['group6']['weight'],
  );

  $form['group6']['billable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Billable'),
    '#default_value' => isset($node->billable) ? $node->billable : variable_get('pmtask_billable_default', FALSE),
    '#weight' => 1,
  );

  $form['group6']['billed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Billed'),
    '#default_value' => isset($node->billed) ? $node->billed : FALSE,
    '#weight' => 2,
  );

  // Check to see if the body field is still there, if so, display it.
  $body = field_get_items('pmtask', $node, 'body');
  if ($body) {
    $form['body_field'] = $body;
  }

  $form['stepno_old'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($node->stepno_old) ? $node->stepno_old : NULL,
  );

  $form['title_old'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($node->title_old) ? $node->title_old : NULL,
  );

  return $form;
}

/**
 * Ajax callback for the organization nid field on a pmproject node.
 */
function pmtask_ajax_organization_nid(&$form, &$form_state) {
  return $form['group1']['project_nid'];
}

/**
 * Implements hook_insert().
 */
function pmtask_insert($node) {
  _pmtask_beforesave($node);

  db_insert('pmtask')
    ->fields(array(
      'vid' => $node->vid,
      'nid' => $node->nid,
      'stepno' => $node->stepno,
      'taskcategory' => $node->taskcategory,
      'taskstatus' => $node->taskstatus,
      'taskpriority' => $node->taskpriority,
      'organization_nid' => $node->organization_nid,
      'organization_title' => $node->organization_title,
      'project_nid' => $node->project_nid,
      'project_title' => $node->project_title,
      'parent_nid' => $node->parent_nid,
      'weight' => $node->weight,
//      'datebegin' => $node->datebegin,
//      'dateend' => $node->dateend,
      'durationunit' => $node->durationunit,
//      'duration' => $node->duration,
      'pricemode' => $node->pricemode,
//      'price' => $node->price,
      'currency' => $node->currency,
      'assigned_nid' => $node->assigned_nid,
      'assigned_title' => $node->assigned_title,
      'billable' => $node->billable,
      'billed' => $node->billed,
    ))
    ->execute();
}

/**
 * Implements hook_update().
 */
function pmtask_update($node) {
  $org_query = db_select('node', 'n');
  $org_query->join('pmorganization', 'sor', 'n.vid = sor.vid');
  $org_result = $org_query
    ->fields('n', array('title'))
    ->condition('n.type', 'pmorganization')
    ->condition('n.nid', $node->organization_nid)
    ->execute();

  $o = $org_result->fetchObject();
  $node->organization_title = $o->title;

  $pro_query = db_select('node', 'n');
  $pro_query->join('pmproject', 'spr', 'n.vid = spr.vid');
  $pro_result = $pro_query
    ->fields('n', array('title'))
    ->condition('n.type', 'pmproject')
    ->condition('n.nid', $node->project_nid)
    ->execute();

  $p = $pro_result->fetchObject();
  $node->project_title = $p->title;

  if ($node->project_nid != $node->project_nid_old) {
    module_invoke_all('pmtask_change_hierarchy', $node->nid, $node->organization_nid, $node->organization_title, $node->project_nid, $node->project_title);
  }
  // if this is a new node or we're adding a new revision,
  if ($node->revision) {
    pmtask_insert($node);
  }
  else {
    _pmtask_beforesave($node);

  db_update('pmtask')
    ->fields(array(
      'stepno' => $node->stepno,
      'taskcategory' => $node->taskcategory,
      'taskstatus' => $node->taskstatus,
      'taskpriority' => $node->taskpriority,
      'organization_nid' => $node->organization_nid,
      'organization_title' => $node->organization_title,
      'project_nid' => $node->project_nid,
      'project_title' => $node->project_title,
      'parent_nid' => $node->parent_nid,
      'weight' => $node->weight,
//      'datebegin' => $node->datebegin,
//      'dateend' => $node->dateend,
      'durationunit' => $node->durationunit,
//      'duration' => $node->duration,
      'pricemode' => $node->pricemode,
//      'price' => $node->price,
      'currency' => $node->currency,
      'assigned_nid' => $node->assigned_nid,
      'assigned_title' => $node->assigned_title,
      'billable' => $node->billable,
      'billed' => $node->billed,
    ))
    ->condition('vid', $node->vid)
    ->execute();

    if (($node->title != $node->title_old) || ($node->stepno != $node->stepno_old)) {
      module_invoke_all('pmtask_change', $node->nid, $node->title, $node->stepno);
    }
  }
}

/**
 * Prepares pmtask for saving.
 */
function _pmtask_beforesave(&$node) {
  $org_query = db_select('node', 'n');
  $org_query->join('pmorganization', 'sor', 'n.vid = sor.vid');
  $org_result = $org_query
    ->fields('n', array('title'))
    ->condition('n.type', 'pmorganization')
    ->condition('n.nid', $node->organization_nid)
    ->execute();

  $o = $org_result->fetchObject();
  $node->organization_title = $o->title;

  $pro_query = db_select('node', 'n');
  $pro_query->join('pmproject', 'spr', 'n.vid = spr.vid');
  $pro_result = $pro_query
    ->fields('n', array('title'))
    ->fields('spr', array('organization_title'))
    ->condition('n.type', 'pmproject')
    ->condition('n.nid', $node->project_nid)
    ->execute();

  $p = $pro_result->fetchObject();
  $node->project_title = $p->title;

  $assigned = node_load($node->assigned_nid);
  $node->assigned_title = isset($assigned->title) ? $assigned->title : NULL;

  // Allow use of comma when inputting numerical values - str_replace with period decimal
  $node->duration = str_replace(',', '.', $node->duration);
  $node->price = str_replace(',', '.', $node->price);

  if (is_array($node->datebegin)) {
      $node->datebegin = _pm_date_to_gmtimestamp($node->datebegin);
  }
  else {
      $node->datebegin = strtotime($node->datebegin);
  }

  if (is_array($node->dateend)) {
      $node->dateend = _pm_date_to_gmtimestamp($node->dateend);
  }
  else {
      $node->dateend = strtotime($node->dateend);
  }
}

/**
 * Implements hook_node_prepare().
 */
function pmtask_node_prepare($node) {
  if (!isset($node->nid)) {
    $node->iscustomer = 1;
    $node->isactive = 1;

    $taskcategory_list = pm_attributes_bydomain('Task category');
    $node->taskcategory = $taskcategory_list['default'];

    $taskstatus_list = pm_attributes_bydomain('Task status');
    $node->taskstatus = $taskstatus_list['default'];

    $taskpriority_list = pm_attributes_bydomain('Task priority');
    $node->taskpriority = $taskpriority_list['default'];

    $durationunit_list = pm_attributes_bydomain('Duration unit');
    $node->durationunit = $durationunit_list['default'];

    $pricemode_list = pm_attributes_bydomain('Price mode');
    $node->pricemode = $pricemode_list['default'];

    $currency_list = pm_attributes_bydomain('Currency');
    $node->currency = $currency_list['default'];
  }
}

/**
 * Implements hook_node_revision_delete().
 */
function pmtask_node_revision_delete($node) {
  // Notice that we're matching a single revision based on the node's vid.
  db_delete('pmtask')
    ->condition('vid', $node->vid)
    ->execute();
}

/**
 * Implements hook_delete().
 */
function pmtask_delete($node) {
  // Notice that we're matching all revision, by using the node's nid.
  db_delete('pmtask')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_load().
 */
function pmtask_load($nodes) {
  foreach ($nodes as $nid => &$node) {
    $result = db_select('pmtask', 'sta')
      ->fields('sta')
      ->condition('vid', $node->vid)
      ->execute();
    $record = $result->fetchAssoc();

    foreach ($record as $key => $value) {
      $node->$key = $value;
    }

    $node->title_old = $node->title;
    $node->stepno_old = isset($node->stepno) ? $node->stepno : NULL;
  }
}

/**
 * Implements hook_validate().
 */
function pmtask_validate(&$node) {
  if (($node->nid == $node->parent_nid) && $node->parent_nid) {
    form_set_error('parent_nid', t('Impossible to assign itself as parent.'));
  }
}

/**
 * Implements hook_view().
 */
function pmtask_view($node, $view_mode) {
  $breadcrumb = array();
  $breadcrumb[] = l(t('Project Management'), 'pm');
  $breadcrumb[] = l(t('Tasks'), 'pm/tasks');
  drupal_set_breadcrumb($breadcrumb);

  return theme('pmtask_view', array('node' => $node, 'view_mode' => $view_mode));
}

/**
 * Determines whether the task tab of a project is visible.
 */
function _pmtask_tasks_access($node=NULL) {
  if ($node == NULL) return FALSE;
  if ($node->type == 'pmproject' && user_access('Project Management Task: access')) return TRUE;
  return FALSE;
}

/**
 * Provides a tree of tasks for a given project and (if selected) parent task.
 */
function _pmtask_get_tree($project_nid, $parent_nid = 0, $depth = -1, $max_depth = NULL, $where = NULL, $args = array()) {
  static $children, $parents, $tasks;

  $depth++;
  // We cache trees, so it's not CPU-intensive to call get_tree() on a term
  // and its children, too.
  if (!isset($children[$project_nid])) {
    $children[$project_nid] = array();

    $args = array_merge($args, array($project_nid));

    $query = db_select('node', 'n');
    $query->join('pmtask', 'pmta', 'n.vid = pmta.vid');
    $query
      ->fields('n', array('title', 'uid'))
      ->fields('pmta')
      ->condition('n.status', 1)
      ->condition('n.type', 'pmtask')
      ->condition('pmta.project_nid', $args)
      ->addTag('node_access')
      ->addTag('pmtask')
      ->orderBy('pmta.weight', 'ASC');
    $result = $query->execute();

    foreach ($result as $task) {
      $children[$project_nid][$task->parent_nid][] = $task->nid;
      $parents[$project_nid][$task->nid][] = $task->parent_nid;
      $tasks[$project_nid][$task->nid] = $task;
    }
  }

  $max_depth = (is_null($max_depth)) ? count($children[$project_nid]) : $max_depth;
  if (isset($children[$project_nid][$parent_nid]) && $children[$project_nid][$parent_nid]) {
    foreach ($children[$project_nid][$parent_nid] as $child_nid) {
      if ($max_depth > $depth) {
        $task = clone($tasks[$project_nid][$child_nid]);
        $task->depth = $depth;
        $task->parents = $parents[$project_nid][$child_nid];
        $tree[] = $task;
        if (isset($children[$project_nid][$child_nid])) {
          $tree = array_merge($tree, _pmtask_get_tree($project_nid, $child_nid, $depth, $max_depth, $where, $args));
        }
      }
    }
  }
  return isset($tree) ? $tree : array();
}

/**
 * Provides task details for tasks within a tree.
 */
function _pmtask_plain_tree($tree) {
  $rows = array();
  foreach ($tree as $item) {
    $nid = $item->nid;
    $title = check_plain($item->title);
    if ($item->stepno) $title = check_plain($item->stepno) . ' ' . $title;
    if ($nid) $rows[$nid] = str_repeat('--', $item->depth) . ' ' . $title;
  }
  return $rows;
}

/**
 * Implements hook_views_api().
 */
function pmtask_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'pmtask'),
  );
}

/**
 * Creates an invoice based on a selected task.
 */
function pmtask_pminvoice_auto_add($node, $invoice_nid = NULL) {
  if (!module_exists('pminvoice')) {
    drupal_set_message(t('This function should only be called from within Project Management Invoice'));
    return;
  }
  elseif ($node->billed) {
    drupal_set_message(t('This task has already been billed!'));
    return;
  }
  elseif (!$node->billable) {
    drupal_set_message(t('This task is marked unbillable!'));
    return;
  }
  else {
    global $user;

    if (!$invoice_nid) {

      $new_invoice = new StdClass;

      // Code copied with edits from node form
      $new_invoice->requestdate = time();
      $new_invoice->duedate = $new_invoice->requestdate + (variable_get('pminvoice_payment_days', 30) * 86400);
      $new_invoice->number = pminvoice_get_invoice_number($new_invoice->requestdate);

      $new_invoice->title = $node->title;
      $new_invoice->uid = $user->uid;
      $new_invoice->type = 'pminvoice';
      // $new_invoice->reference
      $new_invoice->organization_nid = $node->organization_nid;
      $new_invoice->organization_title = $node->organization_title;
      $new_invoice->project_nid = $node->project_nid;
      $new_invoice->project_title = $node->project_title;
      // $new_invoice->amount
      // $new_invoice->tax
      // $new_invoice->total
      // $new_invoice->totalcustomercurr
      // $new_invoice->taxexempt
      $new_invoice->src_nid = $node->nid;
      $new_invoice->src_vid = $node->vid;

      node_save($new_invoice);
      $invoice_nid = $new_invoice->nid;
    }
    else {
      $new_invoice = node_load($invoice_nid);
    }

    $rate_array = array('pricemode_used' => '', 'rate_to_use' => 0);

    $rate_array = pminvoice_get_rate($node);

    $count = count($new_invoice->items);

    $new_invoice->items[$count]->description = pminvoice_get_item_desc($rate_array, $node);

    $new_invoice->items[$count]->amount = pminvoice_get_item_amount($rate_array, $node);

    // Tax percent simply uses default at the moment
    $new_invoice->items[$count]->tax1percent = variable_get('pm_tax1_percent', 20);
    // $new_invoice_item->items[$count]->tax1
    // $new_invoice_item->items[$count]->total
    $new_invoice->items[$count]->src_nid = $node->nid;
    $new_invoice->items[$count]->src_vid = $node->vid;

    pm_taxation($new_invoice->items[$count]);
    pminvoice_update($new_invoice);
  }

  // Mark task as billed.
  db_query("UPDATE {pmtask} SET billed=%d WHERE vid=%d", 1, $node->vid);

  return $invoice_nid;
}

/**
 * Implements hook_token_list().
 */
function pmtask_token_list($type='all') {
  $tokens = array();
  if (($type == 'node') || ($type == 'all')) {
    $tokens['node']['pmtask-step-no'] = t('Project Management Task: Step No.');
    $tokens['node']['pmtask-organization-nid'] = t('Project Management Task: Organization Node ID.');
    $tokens['node']['pmtask-organization-title'] = t('Project Management Task: Organization Title.');
    $tokens['node']['pmtask-project-nid'] = t('Project Management Task: Project Node ID.');
    $tokens['node']['pmtask-project-title'] = t('Project Management Task: Project Title.');
    $tokens['node']['pmtask-parent-nid'] = t('Project Management Task: Parent NID.');
    $tokens['node']['pmtask-taskstatus'] = t('Project Management Task: Project Status.');
    $tokens['node']['pmtask-taskcategory'] = t('Project Management Task: Task Category.');
    $tokens['node']['pmtask-taskpriority'] = t('Project Management Task: Task Priority.');
    $tokens['node']['pmtask-durationunit'] = t('Project Management Task: Task Duration Unit.');
    $tokens['node']['pmtask-duration'] = t('Project Management Task: Task Duration.');
    $tokens['node']['pmtask-datebegin'] = t('Project Management Task: Task Begin Date.');
    $tokens['node']['pmtask-dateend'] = t('Project Management Task: Task End Date.');
    $tokens['node']['pmtask-billable'] = t('Project Management Task: Task Billable.');
    $tokens['node']['pmtask-billed'] = t('Project Management Task: Task Billed.');
    $tokens['node']['pmtask-price'] = t('Project Management Task: Task Price.');
    $tokens['node']['pmtask-pricemode'] = t('Project Management Task: Task Price Mode.');
    if (module_exists('pmperson')) {
      // Assignee(s)
      $tokens['node']['pmtask-assigned-to-email'] = t('Project Management Task: Task Assignee(s) Email Address(s).');
      $tokens['node']['pmtask-assigned-title'] = t('Project Management Task: Task Assignee(s) Title(s).');
    }
  }
  return $tokens;
}

/**
 * Implements hook_token_values().
 */
function pmtask_token_values($type, $object = NULL) {
  $values = array();
  $node = $object;
  if ((($type == 'node') || ($type == 'all')) && ($node->type === 'pmtask')) {
    $values['pmtask-stepno'] = $node->stepno;
    $values['pmtask-organization-nid'] = $node->organization_nid;
    $values['pmtask-organization-title'] = $node->organization_title;
    $values['pmtask-project-nid'] = $node->project_nid;
    $values['pmtask-project-title'] = $node->project_title;
    $values['pmtask-parent-nid'] = $node->parent_nid;
    $values['pmtask-taskstatus'] = $node->taskstatus;
    $values['pmtask-taskpriority'] = $node->taskpriority;
    $values['pmtask-taskcategory'] = $node->taskcategory;
    $values['pmtask-durationunit'] = $node->durationunit;
    $values['pmtask-duration'] = $node->duration;
    $values['pmtask-datebegin'] = format_date($node->datebegin, 'medium', '', variable_get('date_default_timezone', NULL));
    $values['pmtask-dateend'] = format_date($node->dateend, 'medium', '', variable_get('date_default_timezone', NULL));
    $values['pmtask-price'] = $node->price;
    $values['pmtask-pricemode'] = $node->pricemode;
    $values['pmtask-billable'] = $node->billable;
    $values['pmtask-billed'] = $node->billed;
    if (module_exists('pmperson')) {
      // Project Assignee(s) e-mail
      if ($node->assigned_nid) {
        $values['pmtask-assigned-title'] = $node->assigned_title;
        $assignees_node = node_load($node->assigned_nid);
        // Assigned to one person
        if ($assignees_node->type === 'pmperson') {
          $values['pmtask-assigned-to-email'] = pmperson_primary_email($assignees_node);
        }
        // Assigned to a team
        else {
          $assignees_array = $assignees_node->members_array;
          $assignees = array();
          foreach ($assignees_array as $nid => $name) {
            $assignee = node_load($nid);
            $assignees[] = pmperson_primary_email($assignee);
          }
          $assigned = implode(", ", $assignees);
          // Return comma separated list of emails
          $values['pmtask-assigned-to-email'] = $assigned;
        }
      }
      else {
        $values['pmtask-assigned-to-email'] = NULL;
      }
    }
  }
  return $values;
}

/**
 * Implements  hook_node_access_records().
 */
function pmtask_node_access_records($node) {
  if (empty($node->status)) {
    // Lets Drupal take care of permission to unpublished nodes.
    return array();
  }
  $type = is_string($node) ? $node : $node->type;
  $grants = array();
  if ($type == 'pmtask') {
    // Project Management Task: view all
    $grants[] = array(
      'realm' => 'pmtask_view_all',
      'gid' => 0,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
    // Project Management Task: view own
    $grants[] = array(
      'realm' => 'pmtask_view_own',
      'gid' => $node->uid,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
    // Project Management Task: view of user organization
    if ( isset($node->organization_nid) && !empty($node->organization_nid)) {
      $grants[] = array(
        'realm' => 'pmtask_view_if_user_organization',
        'gid' => $node->organization_nid,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 0,
      );
    }
    // Project Management Task: view if assigned to task
    if ( isset($node->assigned_nid) && !empty($node->assigned_nid)) {
      $grants[] = array(
        'realm' => 'pmtask_view_if_assigned',
        'gid' => $node->assigned_nid,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 0,
      );
    }

    // Project Management Task: edit all
    $grants[] = array(
      'realm' => 'pmtask_update_all',
      'gid' => 0,
      'grant_view' => 0,
      'grant_update' => 1,
      'grant_delete' => 0,
      'priority' => 0,
    );
    // Project Management Task: edit own
    $grants[] = array(
      'realm' => 'pmtask_update_own',
      'gid' => $node->uid,
      'grant_view' => 0,
      'grant_update' => 1,
      'grant_delete' => 0,
      'priority' => 0,
    );
    // Project Management Task: edit of user organization
    if ( isset($node->organization_nid) && !empty($node->organization_nid)) {
      $grants[] = array(
        'realm' => 'pmtask_update_if_user_organization',
        'gid' => $node->organization_nid,
        'grant_view' => 0,
        'grant_update' => 1,
        'grant_delete' => 0,
        'priority' => 0,
      );
    }
    // Project Management Task: edit if assigned to task
    if ( isset($node->assigned_nid) && !empty($node->assigned_nid)) {
      $grants[] = array(
        'realm' => 'pmtask_update_if_assigned',
        'gid' => $node->assigned_nid,
        'grant_view' => 0,
        'grant_update' => 1,
        'grant_delete' => 0,
        'priority' => 0,
      );
    }
    // Project Management Task: delete all
    $grants[] = array(
      'realm' => 'pmtask_delete_all',
      'gid' => 0,
      'grant_view' => 0,
      'grant_update' => 0,
      'grant_delete' => 1,
      'priority' => 0,
    );
    // Project Management Task: delete own
    $grants[] = array(
      'realm' => 'pmtask_delete_own',
      'gid' => $node->uid,
      'grant_view' => 0,
      'grant_update' => 0,
      'grant_delete' => 1,
      'priority' => 0,
    );
    // Project Management Task: delete of user organization
    if ( isset($node->organization_nid) && !empty($node->organization_nid)) {
      $grants[] = array(
        'realm' => 'pmtask_delete_if_user_organization',
        'gid' => $node->organization_nid,
        'grant_view' => 0,
        'grant_update' => 0,
        'grant_delete' => 1,
        'priority' => 0,
      );
    }
    // Project Management Task: delete if assigned to task
    if ( isset($node->assigned_nid) && !empty($node->assigned_nid)) {
      $grants[] = array(
        'realm' => 'pmtask_delete_if_assigned',
        'gid' => $node->assigned_nid,
        'grant_view' => 0,
        'grant_update' => 0,
        'grant_delete' => 1,
        'priority' => 0,
      );
    }
  }
  return $grants;
}

/**
 * Implements hook_node_grants().
 */
function pmtask_node_grants($account, $op) {

  if (module_exists('pmperson')) {
    _pmperson_user_load($account);
    if (!empty($account->pmteam) AND is_array($account->pmteam)) {
      $assigned_nids = $account->pmteam;
    }
    if (isset($account->pmperson_nid) AND !empty($account->pmperson_nid)) {
      $assigned_nids[] = $account->pmperson_nid;
    }
  }
  $grants = array();
  switch ($op) {
    case 'view':
      if (user_access('Project Management Task: view all', $account)) {
        $grants['pmtask_view_all'] = array(0);
      }
      if (user_access('Project Management Task: view own', $account)) {
        $grants['pmtask_view_own'] = array($account->uid);
      }
      if (user_access('Project Management Task: view of user organization', $account) AND !empty($account->pmorganization_nid)) {
        $grants['pmtask_view_if_user_organization'] = array($account->pmorganization_nid);
      }
      if (isset($account->pmperson_nid)) {
        if (user_access('Project Management Task: view if assigned to task', $account)) {
          $grants['pmtask_view_if_assigned'] = $assigned_nids;
        }
      }
      break;

    case 'update':
      if (user_access('Project Management Task: edit all', $account)) {
        $grants['pmtask_update_all'] = array(0);
      }
      if (user_access('Project Management Task: edit own', $account)) {
        $grants['pmtask_update_own'] = array($account->uid);
      }
      if (user_access('Project Management Task: edit of user organization', $account) AND !empty($account->pmorganization_nid)) {
        $grants['pmtask_update_if_user_organization'] = array($account->pmorganization_nid);
      }
      if (isset($account->pmperson_nid)) {
        if (user_access('Project Management Task: edit if assigned to task', $account)) {
          $grants['pmtask_update_if_assigned'] = $assigned_nids;
        }
      }
      break;

    case 'delete':
      if (user_access('Project Management Task: delete all', $account)) {
        $grants['pmtask_delete_all'] = array(0);
      }
      if (user_access('Project Management Task: delete own', $account)) {
        $grants['pmtask_delete_own'] = array($account->uid);
      }
      if (user_access('Project Management Task: delete of user organization', $account) AND !empty($account->pmorganization_nid)) {
        $grants['pmtask_delete_if_user_organization'] = array($account->pmorganization_nid);
      }
      if (isset($account->pmperson_nid)) {
        if (user_access('Project Management Task: delete if assigned to task', $account)) {
          $grants['pmtask_delete_if_assigned'] = $assigned_nids;
        }
      }
      break;
  }
  return $grants;
}

/**
 * Implements hook_pm_dashboard_links().
 */
function pmtask_pm_dashboard_links($type) {
  $links = array();
  if ($type == 'page' || $type == 'block') {
    $links[] = array(
      'theme' => 'pm_dashboard_link',
      'title' => t('Tasks'),
      'icon' => 'pmtasks',
      'path' => 'pm/tasks',
      'params' => array(),
      'access_arguments' => 'Project Management Task: access',
      'node_type' => 'pmtask',
      'add_type' => 'pmtask',
      'map' => array(),
      'weight' => 5,
    );
  }
  return $links;
}
