<?php

/**
 * @file edgeryders_nav.module
 * Provides navbar customizations for Edgeryders
 */

/**
 * Implements hook_navbar().
 *
 * Add items to the navbar menu.
 *
 * The navbar is a container for administrative and site-global interactive
 * components.
 *
 * The navbar provides a common styling for items denoted by the
 * .navbar-tab class. The theme wrapper navbar_tab_wrapper is provided to wrap
 * a navbar item with the appropriate markup to apply the styling.
 *
 * The navbar provides a construct called a 'tray'. The tray is a container
 * for content. The tray may be associated with a toggle in the administration
 * bar. The toggle shows or hides the tray and is optimized for small and
 * large screens. To create this association, hook_navbar() returns one or
 * more render elements of type 'navbar_item', containing the toggle and tray
 * elements in its 'tab' and 'tray' properties.
 *
 * The following properties are available:
 *   - 'tab': A renderable array.
 *   - 'tray': Optional. A renderable array.
 *   - '#weight': Optional. Integer weight used for sorting navbar items in
 *     administration bar area.
 *
 * This hook is invoked in navbar_pre_render().
 *
 * @return
 *   An array of navbar items, keyed by unique identifiers such as 'home' or
 *   'administration', or the short name of the module implementing the hook.
 *   The corresponding value is a render element of type 'navbar_item'.
 *
 * @see navbar_pre_render()
 * @ingroup navbar_tabs
 */

function edgeryders_nav_navbar()
{
  $items = array();


  // The 'Home' tab is a simple link, which is wrapped in markup associated
  // with a visual tab styling.
  $items['edgeryders'] = array(
    '#type' => 'navbar_item',
    '#attached' => array(
      'css' => array(drupal_get_path('module','edgeryders_nav') . '/css/edgeryders_nav.navbar.icons.css'),
    ),
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Edgeryders'),
      '#href' => '<front>',
      '#options' => array(
        'attributes' => array(
          'title' => t('Home'),
          'class' => array('navbar-icon', 'navbar-icon-edgeryders'),
        ),
      ),
    ),
    '#weight' => 100,
  );
  return $items;
}

/**
 * Implements hook_navbar_alter().
 */
function edgeryders_nav_navbar_alter(&$items)
{
  $items['search']['#attached'] = array(
    'css' => array(drupal_get_path('module','edgeryders_nav') . '/css/edgeryders_nav.navbar.icons.css'),
  );
}